apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: development-api
            imageRepo: 711063385483.dkr.ecr.ap-south-2.amazonaws.com/api-dev
            imageTag: "2957f43-3"
            nameSpace: "dev"
            path: api
            targetRevision: main
          - appName: production-api
            imageRepo: 711063385483.dkr.ecr.ap-south-2.amazonaws.com/api-prod
            imageTag: "38f5d67-4"
            nameSpace: "prod"
            path: api
            targetRevision: main
          
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{appName}}-image={{imageRepo}}:~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.tag: "~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: "https://gitlab.com/Saiprakash02/application-helm-charts1.git"
        targetRevision: "main"
        path: "{{path}}"
        helm:
          parameters:
            - name: "name"
              value: "{{appName}}"
            - name: "namespace"
              value: "{{nameSpace}}"
            - name: "image.repository"
              value: "{{imageRepo}}"
            - name: "image.tag"
              value: "{{imageTag}}"
            - name: "replicaCount"
              value: "1"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
         - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true