apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.configmap.postgresdb | quote }}
  POSTGRES_USER: {{ .Values.configmap.postgresuser | quote }}