apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secrets.name }}
    namespace: {{ .Values.namespace }}
type: {{ .Values.secrets.type }}
data:
    POSTGRES_PASSWORD: {{ .Values.secrets.postgrespass }}