apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-{{ .Values.name }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: "api-{{ .Values.name }}-container"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsNonRoot: false
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          env:
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: PGPASSWORD

