helm:
  parameters:
  - name: name
    value: development
    forcestring: false
  - name: namespace
    value: dev
    forcestring: false
  - name: image.repository
    value: 711063385483.dkr.ecr.ap-south-2.amazonaws.com/web-dev
    forcestring: false
  - name: image.tag
    value: 7f197d5-7
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 711063385483.dkr.ecr.ap-south-2.amazonaws.com/web-dev
    forcestring: true
